Repository ArtLesUe/czysty-kod-projekt-zaliczeniowy, pull requests merged in 2022-12, with the labels that each got.

#74 feature/#73
  CkpTodoApp/Controllers/User/UserEditController.cs
  CkpTodoApp/Controllers/User/UserPasswordController.cs
  CkpTodoApp/Requests/UserRegisterRequest.cs
Labels: bugfix

#77 feature/#76
  CkpTodoApp/Controllers/User/UserDetailsController.cs
Labels: bugfix

#79 feature/#78
  CkpTodoApp/Controllers/User/UserEditController.cs
Labels: bugfix

#82 feature/#71
  CkpTodoApp/openapi.yaml
Labels: feature

#85 feature/#84
  CkpTodoApp/Models/ApiUserModel.cs
Labels: bugfix

#87 feature/#86
  CkpTodoApp/Controllers/Task/AddTaskController.cs
Labels: bugfix

#90 feature/#70
  CkpTodoApp/Controllers/User/UserDetailsController.cs
  CkpTodoApp/Models/ApiUserModel.cs
  CkpTodoTests/.env
  CkpTodoTests/.gitignore
  CkpTodoTests/001.auth.post.api.user.login.test.js
  CkpTodoTests/002.user.get.api.user.list.test.js
  CkpTodoTests/003.user.post.api.user.register.test.js
  CkpTodoTests/004.user.get.api.user.delete.id.test.js
  CkpTodoTests/005.task.get.api.tasks.list.test.js
  CkpTodoTests/006.task.post.api.task.add.test.js
  CkpTodoTests/007.task.post.api.task.edit.id.test.js
  CkpTodoTests/008.task.get.api.task.delete.id.test.js
  CkpTodoTests/009.task.get.api.task.check.id.test.js
  CkpTodoTests/010.event.get.api.events.list.test.js
  CkpTodoTests/011.event.post.api.events.add.test.js
  CkpTodoTests/012.event.post.api.events.edit.id.test.js
  CkpTodoTests/013.event.get.api.events.delete.id.test.js
  CkpTodoTests/014.profile.get.api.user.details.id.test.js
  CkpTodoTests/015.profile.post.api.user.edit.id.test.js
  CkpTodoTests/016.profile.post.api.user.password.id.test.js
  CkpTodoTests/README.md
  CkpTodoTests/package-lock.json
  CkpTodoTests/package.json
  README.md
Labels: feature

#92 feature/#91
  CkpTodoApp/Controllers/Event/AddEventController.cs
  CkpTodoApp/Controllers/Event/DeleteEventController.cs
  CkpTodoApp/Controllers/Event/EditEventController.cs
  CkpTodoApp/Controllers/Event/TasksEventController.cs
  CkpTodoApp/Controllers/RootController.cs
  CkpTodoApp/Controllers/Task/AddTaskController.cs
  CkpTodoApp/Controllers/Task/CheckTaskController.cs
  CkpTodoApp/Controllers/Task/DeleteTaskController.cs
  CkpTodoApp/Controllers/Task/EditTaskController.cs
  CkpTodoApp/Controllers/Task/TasksListController.cs
  CkpTodoApp/Controllers/User/UserDeleteController.cs
  CkpTodoApp/Controllers/User/UserDetailsController.cs
  CkpTodoApp/Controllers/User/UserEditController.cs
  CkpTodoApp/Controllers/User/UserListController.cs
  CkpTodoApp/Controllers/User/UserLoginTokenController.cs
  CkpTodoApp/Controllers/User/UserPasswordController.cs
  CkpTodoApp/Controllers/User/UserRegisterController.cs
  CkpTodoApp/Program.cs
Labels: bugfix

#98 change/#68
  CkpTodoApp/Commons/Md5HashGenerator.cs
  CkpTodoApp/Commons/StatusCodeEnum.cs
  CkpTodoApp/Controllers/Event/AddEventController.cs
  CkpTodoApp/Controllers/Event/DeleteEventController.cs
  CkpTodoApp/Controllers/Event/EditEventController.cs
  CkpTodoApp/Controllers/Event/EventListController.cs
  CkpTodoApp/Controllers/RootController.cs
  CkpTodoApp/Controllers/Task/AddTaskController.cs
  CkpTodoApp/Controllers/Task/AddTaskService.cs
  CkpTodoApp/Controllers/Task/CheckTaskController.cs
  CkpTodoApp/Controllers/Task/DeleteTaskController.cs
  CkpTodoApp/Controllers/Task/EditTaskController.cs
  CkpTodoApp/Controllers/Task/TasksListController.cs
  CkpTodoApp/Controllers/User/UserDeleteController.cs
  CkpTodoApp/Controllers/User/UserDetailsController.cs
  CkpTodoApp/Controllers/User/UserEditController.cs
  CkpTodoApp/Controllers/User/UserListController.cs
  CkpTodoApp/Controllers/User/UserLoginTokenController.cs
  CkpTodoApp/Controllers/User/UserPasswordController.cs
  CkpTodoApp/Controllers/User/UserRegisterController.cs
  CkpTodoApp/Services/AuthService/AuthService.cs
  CkpTodoApp/Services/AuthService/IAuthServiceInterface.cs
  CkpTodoApp/openapi.yaml
  CkpTodoTests/003.user.post.api.user.register.test.js
  CkpTodoTests/006.task.post.api.task.add.test.js
  CkpTodoTests/007.task.post.api.task.edit.id.test.js
  CkpTodoTests/008.task.get.api.task.delete.id.test.js
  CkpTodoTests/011.event.post.api.events.add.test.js
  CkpTodoTests/012.event.post.api.events.edit.id.test.js
  CkpTodoTests/013.event.get.api.events.delete.id.test.js
Labels: change
